2025-06-05 17:23:32,751 - app.utils.decorators - INFO - MainThread - Executing: add_student
2025-06-05 17:23:32,753 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:23:32,758 - app.utils.decorators - INFO - MainThread - Executing: save_students
2025-06-05 17:23:32,759 - app.utils.decorators - ERROR - MainThread - Error while Executing: save_students : [Errno 2] No such file or directory: 'data/students.json'
Traceback (most recent call last):
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\utils\decorators.py", line 15, in wrapper
    return func(*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\service\student_service.py", line 20, in save_students
    with open(STUDENT_FILE, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/students.json'
2025-06-05 17:23:32,762 - app.utils.decorators - ERROR - MainThread - Error while Executing: add_student : 400: [Errno 2] No such file or directory: 'data/students.json'
Traceback (most recent call last):
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\utils\decorators.py", line 15, in wrapper
    return func(*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\service\student_service.py", line 20, in save_students
    with open(STUDENT_FILE, 'w') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'data/students.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\utils\decorators.py", line 15, in wrapper
    return func(*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\service\student_service.py", line 28, in add_student
    save_students(students)
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\utils\decorators.py", line 19, in wrapper
    raise HTTPException(status_code = 400,detail= str(e))
fastapi.exceptions.HTTPException: 400: [Errno 2] No such file or directory: 'data/students.json'
2025-06-05 17:25:00,161 - app.utils.decorators - INFO - MainThread - Executing: add_student
2025-06-05 17:25:00,163 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:25:00,167 - app.utils.decorators - INFO - MainThread - Executing: save_students
2025-06-05 17:25:00,169 - app.service.student_service - INFO - MainThread - Students data saved
2025-06-05 17:25:13,060 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:25:41,128 - app.utils.decorators - INFO - MainThread - Executing: delete_students
2025-06-05 17:25:41,130 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:25:41,135 - app.utils.decorators - INFO - MainThread - Executing: save_students
2025-06-05 17:25:41,137 - app.service.student_service - INFO - MainThread - Students data saved
2025-06-05 17:25:43,001 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:25:52,898 - app.utils.decorators - INFO - MainThread - Executing: search_student_by_name
2025-06-05 17:25:52,903 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:26:23,623 - app.utils.decorators - INFO - MainThread - Executing: add_book
2025-06-05 17:26:23,625 - app.utils.decorators - INFO - MainThread - Executing: load_books
2025-06-05 17:26:23,630 - app.utils.decorators - INFO - MainThread - Executing: save_books
2025-06-05 17:26:23,632 - app.service.book_service - INFO - MainThread - Books data saved
2025-06-05 17:26:25,836 - app.utils.decorators - INFO - MainThread - Executing: load_students
2025-06-05 17:27:12,595 - app.utils.decorators - INFO - MainThread - Executing: search_books_by_title
2025-06-05 17:27:12,595 - app.utils.decorators - INFO - MainThread - Executing: load_books
2025-06-05 17:27:12,618 - app.utils.decorators - ERROR - MainThread - Error while Executing: search_books_by_title : 'Book' object is not subscriptable
Traceback (most recent call last):
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\utils\decorators.py", line 15, in wrapper
    return func(*args,**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Gen_AI_Train\Lib_Management_Cli\app\service\book_service.py", line 46, in search_books_by_title
    status = "Available"  if book['available'] else "Issued"
                             ~~~~^^^^^^^^^^^^^
TypeError: 'Book' object is not subscriptable
2025-06-05 17:29:02,322 - app.utils.decorators - INFO - MainThread - Executing: add_book
2025-06-05 17:29:02,324 - app.utils.decorators - INFO - MainThread - Executing: load_books
2025-06-05 17:29:02,329 - app.utils.decorators - INFO - MainThread - Executing: save_books
2025-06-05 17:29:02,331 - app.service.book_service - INFO - MainThread - Books data saved
2025-06-05 17:29:15,087 - app.utils.decorators - INFO - MainThread - Executing: search_books_by_title
2025-06-05 17:29:15,089 - app.utils.decorators - INFO - MainThread - Executing: load_books
